### ISSUE TITLE
Failure on yarn marketlaunch:setup

### ISSUE THREAD

**Issue by sags95** [morrowdigital/MarketLaunch#3]
Looks like I'm not able to compile on the `yarn marketlaunch:setup` step as it throws lots of TS errors. Adding "node" to the "types" in tsconfig.json solved this however.

```
"types": ["reflect-metadata", "node"]
```

**Comment by GnomedDev** [comment]
Removing the field seems to work fine as-well, while reducing complexity and undocumented options we have enabled. Making a PR now.
